name: Build and Release GOSync

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build GOSync EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed --name GOSync `
            --hidden-import "PySide6.QtCore" `
            --hidden-import "PySide6.QtGui" `
            --hidden-import "PySide6.QtWidgets" `
            --hidden-import "paramiko" `
            --hidden-import "cryptography" `
            --hidden-import "scp" `
            --icon=assets/icons/app.ico `
            --add-data "assets;assets" `
            --add-data "themes/ui.qss;themes" `
            --add-data "ui;ui" `
            --add-data "core;core" `
            --add-data "utils;utils" `
            main.py

      - name: Create Release Archive
        run: |
          Compress-Archive -Path "dist/GOSync.exe", "LICENSE", "README.md" -DestinationPath "GOSync-${{ github.ref_name }}-windows.zip"
        shell: pwsh

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: GOSync-${{ github.ref_name }}-windows.zip
          body: |
            GOSync ${{ github.ref_name }} Windows Release
            
            ## System Requirements
            - Windows
            - No additional Python installation needed (standalone executable)
            
            ## Features
            - Secure SSH file backup and sync
            - Encrypted settings storage
            - Modern UI with system tray support
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 